---
- hosts: all

  vars_files:
    - ../vagrant.yml

  roles:
    - role: elnebuloso.package-upgrade

    - role: geerlingguy.ntp
    - role: elnebuloso.docker
    - role: elnebuloso.docker-compose
    - role: elnebuloso.docker-pip

    - role: elnebuloso.package-cleanup

  post_tasks:
    - docker_login:
        registry_url: "{{item.docker_login_registry_url}}"
        username: "{{item.docker_login_username}}"
        password: "{{item.docker_login_password}}"
      with_items: "{{docker_logins}}"