---
- hosts: all

  vars_files:
    - ../vagrant.yml

  roles:
    - role: elnebuloso.package-upgrade

    - role: geerlingguy.ntp
    - role: elnebuloso.docker
    - role: elnebuloso.docker-compose

    - role: elnebuloso.package-cleanup